### PR TITLE
Update API endpoints

### PR DESCRIPTION
**Pull request by corafid**
Update the API endpoints in the SDK to match the recent changes to the API done in https://github.com/cohere-ai/compass/pull/567.

### CODE REVIEW

**Comment by luca-cohere** [comment]
The unit tests are failing, some mock testing the calls.

**Comment by luca-cohere** [comment]
Change itself LGTM, perhaps we want to change `push_documents` to `upload_documents` but we can have a second PR for that, up to you.

**Comment by corafid** [comment]
> The unit tests are failing, some mock testing the calls.

Fixed.

**Comment by corafid** [comment]
> Change itself LGTM, perhaps we want to change `push_documents` to `upload_documents` but we can have a second PR for that, up to you.

Good point. Renamed "push" to "upload".

**Comment by luca-cohere** [comment]
There is some naming discussion [classical last min :( ] do you mind holding this for an extra hour?

**Comment by luca-cohere** [comment]
There is only one change missing:

https://github.com/cohere-ai/compass/blob/fcf3484d25b5b7230cb3f7ae97565f0cfae92131/api/src/api/server.py#L579

check the paremeters of the Upload, done that I can approve. Thanks a lot.

**Comment by corafid** [comment]
> There is only one change missing:
> 
> https://github.com/cohere-ai/compass/blob/fcf3484d25b5b7230cb3f7ae97565f0cfae92131/api/src/api/server.py#L579
> 
> check the paremeters of the Upload, done that I can approve. Thanks a lot.

Done.

**Pull request merged**
